[theme]
base = "dark"
primaryColor = "#c5cedb"
backgroundColor = "#08090c"
secondaryBackgroundColor = "#101218"
textColor = "#eceef2"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"